import { Comment } from '../models/comment.model'

export const COMMENTS: Comment[] = [
  {
    id: '7',
    targetType: 'community',
    targetId: '1',
    author: 'Valeera',
    content: 'This route made our first Deadmines run much smoother, especially once we stopped skipping the ship patrols.',
    createdAt: '2026-07-10T17:30:00.000Z',
    likeCount: 5,
  },
  {
    id: '8',
    targetType: 'community',
    targetId: '1',
    parentId: '7',
    author: 'Mirael',
    content: 'The ship section was where our group improved the most too.',
    createdAt: '2026-07-10T17:48:00.000Z',
    likeCount: 3,
  },
  {
    id: '10',
    targetType: 'community',
    targetId: '1',
    parentId: '8',
    author: 'DeckhandDan',
    content: 'Clearing each deck gives the healer a safe fallback position.',
    createdAt: '2026-07-10T18:02:00.000Z',
    likeCount: 2,
  },
  {
    id: '11',
    targetType: 'community',
    targetId: '1',
    parentId: '8',
    author: 'Mirael',
    content: 'Exactly, and it prevents someone from backing into an untouched patrol.',
    createdAt: '2026-07-10T18:14:00.000Z',
    likeCount: 1,
  },
  {
    id: '9',
    targetType: 'community',
    targetId: '1',
    parentId: '7',
    author: 'Stonepaw',
    content: 'What level was your tank? We struggled with the same pulls at level 18.',
    createdAt: '2026-07-10T18:25:00.000Z',
    likeCount: 4,
  },
  {
    id: '12',
    targetType: 'community',
    targetId: '1',
    parentId: '9',
    author: 'Valeera',
    content: 'Our tank was 19 with mostly Westfall quest rewards.',
    createdAt: '2026-07-10T18:39:00.000Z',
    likeCount: 2,
  },
  {
    id: '13',
    targetType: 'community',
    targetId: '1',
    parentId: '9',
    author: 'Shieldmaiden',
    content: 'Level 19 feels much more forgiving for a first-time tank.',
    createdAt: '2026-07-10T18:51:00.000Z',
    likeCount: 5,
  },
  {
    id: '14',
    targetType: 'community',
    targetId: '1',
    parentId: '9',
    author: 'Stonepaw',
    content: 'That explains it. I will grab another level before our next attempt.',
    createdAt: '2026-07-10T19:06:00.000Z',
    likeCount: 1,
  },
  {
    id: '15',
    targetType: 'community',
    targetId: '1',
    author: 'Fizzcrank',
    content: 'Marking the Engineers before each Foundry pull made the route much safer for us.',
    createdAt: '2026-07-11T09:20:00.000Z',
    likeCount: 8,
  },
  {
    id: '16',
    targetType: 'community',
    targetId: '1',
    author: 'Elowyn',
    content: 'The reminder to clear bag space deserves emphasis. Those quest drops fill the last few slots quickly.',
    createdAt: '2026-07-11T12:35:00.000Z',
    likeCount: 6,
  },
  {
    id: '17',
    targetType: 'community',
    targetId: '1',
    author: 'Rendall',
    content: 'A short faction-specific quest checklist would be a useful addition to this guide.',
    createdAt: '2026-07-11T16:10:00.000Z',
    likeCount: 4,
  },
  {
    id: '5',
    targetType: 'community',
    targetId: '2',
    author: 'Cenarius',
    content: 'The connection to the world trees is especially interesting.',
    createdAt: '2026-07-09T11:10:00.000Z',
    likeCount: 9,
  },
  {
    id: '6',
    targetType: 'community',
    targetId: '3',
    author: 'Throm-Ka',
    content: 'Clear role assignments helped our group more than extra gear.',
    createdAt: '2026-07-06T19:05:00.000Z',
    likeCount: 4,
  },
]
