import { News } from '../models/news.model'

export const NEWS: News[] = [
  {
    id: '1',
    title: 'WoW Classic',
    summary: 'Return to Azeroth and relive the original World of Warcraft experience.',
    content: 'WoW Classic brings the foundational adventures, lands, and legends of Azeroth back into focus for veterans and new adventurers alike.',
    category: 'News',
    author: 'WoWiki Editors',
    updatedAt: '2026-07-10T12:00:00.000Z',
    imageUrl: '/images/wow_classic_logo.png',
    viewerCount: 24891,
  },
  {
    id: '2',
    title: "The Fall of Quel'Thalas",
    summary: 'An illustrated deep-dive into the Battle for Silvermoon and its aftermath.',
    content: "Quel'Thalas, the home of the high elves, stood proud for millennia. This article traces the political tensions, the military campaigns, and the tragic fall that reshaped Azeroth's history.",
    category: 'Lore',
    author: 'Archivist',
    updatedAt: '2026-07-07T00:00:00.000Z',
    viewerCount: 18342,
  },
  {
    id: '3',
    title: 'The Council of Three Hammers Reunites',
    summary: 'Ironforge prepares for a new chapter as its three ruling clans meet beneath the High Seat.',
    content: 'Representatives of the Bronzebeard, Wildhammer, and Dark Iron clans have convened in Ironforge to address the growing threats beyond Khaz Modan and renew their shared commitment to the city.',
    category: 'World Update',
    author: 'Brom Silverbeard',
    updatedAt: '2026-07-08T00:00:00.000Z',
    viewerCount: 12796,
  },
  {
    id: '4',
    title: 'Patch Notes: Defenders of Azeroth',
    summary: 'Class adjustments, dungeon refinements, and quality-of-life changes arrive this week.',
    content: 'This update refines several class abilities, adjusts encounters in Blackrock Depths, and introduces clearer quest tracking for adventurers returning to Azeroth.',
    category: 'Patch Notes',
    author: 'WoWiki Editors',
    updatedAt: '2026-07-08T12:00:00.000Z',
    viewerCount: 20461,
  },
  {
    id: '5',
    title: 'A Guide to the Emerald Dream',
    summary: 'Explore the wild heart of Azeroth and the ancient forces that watch over it.',
    content: 'The Emerald Dream reflects Azeroth as it might have been: untamed, vibrant, and guarded by the Green Dragonflight. Our guide traces its origins, notable regions, and most enduring mysteries.',
    category: 'Guide',
    author: 'Letharion Grovekeeper',
    updatedAt: '2026-07-09T00:00:00.000Z',
    viewerCount: 15873,
  },
  {
    id: '6',
    title: 'The Frostwolf Clan Returns to Alterac',
    summary: 'Scouts report renewed activity around the ancestral homeland of the Frostwolf orcs.',
    content: 'Frostwolf scouts have returned to Alterac Valley to reinforce old alliances and survey the passes ahead of winter. The clan asks travelers to respect the valley and its contested history.',
    category: 'World Update',
    author: 'Drek\'Thar',
    updatedAt: '2026-07-09T09:00:00.000Z',
    viewerCount: 10926,
  },
  {
    id: '7',
    title: 'Remembering the Guardians of Teldrassil',
    summary: 'A record of the sentinels, druids, and civilians who defended the kaldorei homeland.',
    content: 'The night elves preserve the stories of those who stood for Teldrassil. This collection gathers eyewitness accounts and honors the resilience of a people rebuilding their future.',
    category: 'Lore',
    author: 'Sister Althea',
    updatedAt: '2026-07-10T00:00:00.000Z',
    viewerCount: 14208,
  },
]
