import { ClassTalents } from '../models/talent'

export const WARRIOR_TALENT_SOURCE = 'https://static.icy-veins.com/json/classic-talent-calculator/warrior.json'

export const WARRIOR_TALENTS: ClassTalents = {
  classId: 'warrior',
  className: 'Warrior',
  color: '#c69b6d',
  version: 'classic-era',
  maxLevel: 60,
  maxTalentPoints: 51,
  trees: [
    {
      id: 'warrior-arms',
      name: 'Arms',
      order: 0,
      talents: [
        {
          id: 'warrior-arms-improved-heroic-strike',
          name: 'Improved Heroic Strike',
          icon: 'ability_rogue_ambush',
          row: 0,
          column: 0,
          requiredPoints: 0,
          maxRank: 3,
          ranks: [
            { spellId: 12282, description: 'Reduces the cost of your Heroic Strike ability by 1 rage point.' },
            { spellId: 12663, description: 'Reduces the cost of your Heroic Strike ability by 2 rage points.' },
            { spellId: 12664, description: 'Reduces the cost of your Heroic Strike ability by 3 rage points.' }
          ],
        },
        {
          id: 'warrior-arms-deflection',
          name: 'Deflection',
          icon: 'ability_parry',
          row: 0,
          column: 1,
          requiredPoints: 0,
          maxRank: 5,
          ranks: [
            { spellId: 16462, description: 'Increases your Parry chance by 1%.' },
            { spellId: 16463, description: 'Increases your Parry chance by 2%.' },
            { spellId: 16464, description: 'Increases your Parry chance by 3%.' },
            { spellId: 16465, description: 'Increases your Parry chance by 4%.' },
            { spellId: 16466, description: 'Increases your Parry chance by 5%.' }
          ],
        },
        {
          id: 'warrior-arms-improved-rend',
          name: 'Improved Rend',
          icon: 'ability_gouge',
          row: 0,
          column: 2,
          requiredPoints: 0,
          maxRank: 3,
          ranks: [
            { spellId: 12286, description: 'Increases the bleed damage done by your Rend ability by 15%.' },
            { spellId: 12658, description: 'Increases the bleed damage done by your Rend ability by 25%.' },
            { spellId: 12659, description: 'Increases the bleed damage done by your Rend ability by 35%.' }
          ],
        },
        {
          id: 'warrior-arms-improved-charge',
          name: 'Improved Charge',
          icon: 'ability_warrior_charge',
          row: 1,
          column: 0,
          requiredPoints: 5,
          maxRank: 2,
          ranks: [
            { spellId: 12285, description: 'Increases the amount of rage generated by your Charge ability by 3.' },
            { spellId: 12697, description: 'Increases the amount of rage generated by your Charge ability by 6.' }
          ],
        },
        {
          id: 'warrior-arms-tactical-mastery',
          name: 'Tactical Mastery',
          icon: 'spell_nature_enchantarmor',
          row: 1,
          column: 1,
          requiredPoints: 5,
          maxRank: 5,
          ranks: [
            { spellId: 12295, description: 'You retain up to 5 of your rage points when you change stances.' },
            { spellId: 12676, description: 'You retain up to 10 of your rage points when you change stances.' },
            { spellId: 12677, description: 'You retain up to 15 of your rage points when you change stances.' },
            { spellId: 12678, description: 'You retain up to 20 of your rage points when you change stances.' },
            { spellId: 12679, description: 'You retain up to 25 of your rage points when you change stances.' }
          ],
        },
        {
          id: 'warrior-arms-improved-thunder-clap',
          name: 'Improved Thunder Clap',
          icon: 'ability_thunderclap',
          row: 1,
          column: 3,
          requiredPoints: 5,
          maxRank: 3,
          ranks: [
            { spellId: 12287, description: 'Reduces the cost of your Thunder Clap ability by 1 rage point.' },
            { spellId: 12665, description: 'Reduces the cost of your Thunder Clap ability by 2 rage points.' },
            { spellId: 12666, description: 'Reduces the cost of your Thunder Clap ability by 4 rage points.' }
          ],
        },
        {
          id: 'warrior-arms-improved-overpower',
          name: 'Improved Overpower',
          icon: 'inv_sword_05',
          row: 2,
          column: 0,
          requiredPoints: 10,
          maxRank: 2,
          ranks: [
            { spellId: 12290, description: 'Increases the critical strike chance of your Overpower ability by 25%.' },
            { spellId: 12963, description: 'Increases the critical strike chance of your Overpower ability by 50%.' }
          ],
        },
        {
          id: 'warrior-arms-anger-management',
          name: 'Anger Management',
          icon: 'spell_holy_blessingofstamina',
          row: 2,
          column: 1,
          requiredPoints: 10,
          maxRank: 1,
          ranks: [
            { spellId: 12296, description: 'Increases the time required for your rage to decay while out of combat by 30%.' }
          ],
          prerequisite: { talentId: 'warrior-arms-tactical-mastery', requiredRank: 5 },
        },
        {
          id: 'warrior-arms-deep-wounds',
          name: 'Deep Wounds',
          icon: 'ability_backstab',
          row: 2,
          column: 2,
          requiredPoints: 10,
          maxRank: 3,
          ranks: [
            { spellId: 12834, description: 'Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon\'s average damage over 12 seconds.' },
            { spellId: 12849, description: 'Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon\'s average damage over 12 seconds.' },
            { spellId: 12867, description: 'Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon\'s average damage over 12 seconds.' }
          ],
          prerequisite: { talentId: 'warrior-arms-improved-rend', requiredRank: 3 },
        },
        {
          id: 'warrior-arms-two-handed-weapon-specialization',
          name: 'Two-Handed Weapon Specialization',
          icon: 'inv_axe_09',
          row: 3,
          column: 1,
          requiredPoints: 15,
          maxRank: 5,
          ranks: [
            { spellId: 12163, description: 'Increases the damage you deal with two-handed melee weapons by 1%.' },
            { spellId: 12711, description: 'Increases the damage you deal with two-handed melee weapons by 2%.' },
            { spellId: 12712, description: 'Increases the damage you deal with two-handed melee weapons by 3%.' },
            { spellId: 12713, description: 'Increases the damage you deal with two-handed melee weapons by 4%.' },
            { spellId: 12714, description: 'Increases the damage you deal with two-handed melee weapons by 5%.' }
          ],
        },
        {
          id: 'warrior-arms-impale',
          name: 'Impale',
          icon: 'ability_searingarrow',
          row: 3,
          column: 2,
          requiredPoints: 15,
          maxRank: 2,
          ranks: [
            { spellId: 16493, description: 'Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.' },
            { spellId: 16494, description: 'Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%.' }
          ],
          prerequisite: { talentId: 'warrior-arms-deep-wounds', requiredRank: 3 },
        },
        {
          id: 'warrior-arms-axe-specialization',
          name: 'Axe Specialization',
          icon: 'inv_axe_06',
          row: 4,
          column: 0,
          requiredPoints: 20,
          maxRank: 5,
          ranks: [
            { spellId: 12700, description: 'Increases your chance to get a critical strike with Axes by 1%.' },
            { spellId: 12781, description: 'Increases your chance to get a critical strike with Axes by 2%.' },
            { spellId: 12783, description: 'Increases your chance to get a critical strike with Axes by 3%.' },
            { spellId: 12784, description: 'Increases your chance to get a critical strike with Axes by 4%.' },
            { spellId: 12785, description: 'Increases your chance to get a critical strike with Axes by 5%.' }
          ],
        },
        {
          id: 'warrior-arms-sweeping-strikes',
          name: 'Sweeping Strikes',
          icon: 'ability_rogue_slicedice',
          row: 4,
          column: 1,
          requiredPoints: 20,
          maxRank: 1,
          ranks: [
            { spellId: 12292, description: 'Your next 5 melee attacks strike an additional nearby opponent.' }
          ],
        },
        {
          id: 'warrior-arms-mace-specialization',
          name: 'Mace Specialization',
          icon: 'inv_mace_01',
          row: 4,
          column: 2,
          requiredPoints: 20,
          maxRank: 5,
          ranks: [
            { spellId: 12284, description: 'Gives you a 1% chance to stun your target for 3 seconds with a Mace.' },
            { spellId: 12701, description: 'Gives you a 2% chance to stun your target for 3 seconds with a Mace.' },
            { spellId: 12702, description: 'Gives you a 3% chance to stun your target for 3 seconds with a Mace.' },
            { spellId: 12703, description: 'Gives you a 4% chance to stun your target for 3 seconds with a Mace.' },
            { spellId: 12704, description: 'Gives you a 6% chance to stun your target for 3 seconds with a Mace.' }
          ],
        },
        {
          id: 'warrior-arms-sword-specialization',
          name: 'Sword Specialization',
          icon: 'inv_sword_27',
          row: 4,
          column: 3,
          requiredPoints: 20,
          maxRank: 5,
          ranks: [
            { spellId: 12281, description: 'Gives you a 1% chance to get an extra attack on the same target after dealing damage with your Sword.' },
            { spellId: 12812, description: 'Gives you a 2% chance to get an extra attack on the same target after dealing damage with your Sword.' },
            { spellId: 12813, description: 'Gives you a 3% chance to get an extra attack on the same target after dealing damage with your Sword.' },
            { spellId: 12814, description: 'Gives you a 4% chance to get an extra attack on the same target after dealing damage with your Sword.' },
            { spellId: 12815, description: 'Gives you a 5% chance to get an extra attack on the same target after dealing damage with your Sword.' }
          ],
        },
        {
          id: 'warrior-arms-polearm-specialization',
          name: 'Polearm Specialization',
          icon: 'inv_weapon_halbard_01',
          row: 5,
          column: 0,
          requiredPoints: 25,
          maxRank: 5,
          ranks: [
            { spellId: 12165, description: 'Increases your chance to get a critical strike with Polearms by 1%.' },
            { spellId: 12830, description: 'Increases your chance to get a critical strike with Polearms by 2%.' },
            { spellId: 12831, description: 'Increases your chance to get a critical strike with Polearms by 3%.' },
            { spellId: 12832, description: 'Increases your chance to get a critical strike with Polearms by 4%.' },
            { spellId: 12833, description: 'Increases your chance to get a critical strike with Polearms by 5%.' }
          ],
        },
        {
          id: 'warrior-arms-improved-hamstring',
          name: 'Improved Hamstring',
          icon: 'ability_shockwave',
          row: 5,
          column: 2,
          requiredPoints: 25,
          maxRank: 3,
          ranks: [
            { spellId: 12289, description: 'Gives your Hamstring ability a 5% chance to immobilize the target for 5 seconds.' },
            { spellId: 12668, description: 'Gives your Hamstring ability a 10% chance to immobilize the target for 5 seconds.' },
            { spellId: 23695, description: 'Gives your Hamstring ability a 15% chance to immobilize the target for 5 seconds.' }
          ],
        },
        {
          id: 'warrior-arms-mortal-strike',
          name: 'Mortal Strike',
          icon: 'ability_warrior_savageblow',
          row: 6,
          column: 1,
          requiredPoints: 30,
          maxRank: 1,
          ranks: [
            { spellId: 12294, description: 'A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 seconds.' }
          ],
          prerequisite: { talentId: 'warrior-arms-sweeping-strikes', requiredRank: 1 },
        }
      ],
    },
    {
      id: 'warrior-fury',
      name: 'Fury',
      order: 1,
      talents: [
        {
          id: 'warrior-fury-booming-voice',
          name: 'Booming Voice',
          icon: 'spell_nature_purge',
          row: 0,
          column: 1,
          requiredPoints: 0,
          maxRank: 5,
          ranks: [
            { spellId: 12321, description: 'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 10%.' },
            { spellId: 12835, description: 'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 20%.' },
            { spellId: 12836, description: 'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 30%.' },
            { spellId: 12837, description: 'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 40%.' },
            { spellId: 12838, description: 'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 50%.' }
          ],
        },
        {
          id: 'warrior-fury-cruelty',
          name: 'Cruelty',
          icon: 'ability_rogue_eviscerate',
          row: 0,
          column: 2,
          requiredPoints: 0,
          maxRank: 5,
          ranks: [
            { spellId: 12320, description: 'Increases your chance to get a critical strike with melee weapons by 1%.' },
            { spellId: 12852, description: 'Increases your chance to get a critical strike with melee weapons by 2%.' },
            { spellId: 12853, description: 'Increases your chance to get a critical strike with melee weapons by 3%.' },
            { spellId: 12855, description: 'Increases your chance to get a critical strike with melee weapons by 4%.' },
            { spellId: 12856, description: 'Increases your chance to get a critical strike with melee weapons by 5%.' }
          ],
        },
        {
          id: 'warrior-fury-improved-demoralizing-shout',
          name: 'Improved Demoralizing Shout',
          icon: 'ability_warrior_warcry',
          row: 1,
          column: 1,
          requiredPoints: 5,
          maxRank: 5,
          ranks: [
            { spellId: 12324, description: 'Increases the melee attack power reduction of your Demoralizing Shout by 8%.' },
            { spellId: 12876, description: 'Increases the melee attack power reduction of your Demoralizing Shout by 16%.' },
            { spellId: 12877, description: 'Increases the melee attack power reduction of your Demoralizing Shout by 24%.' },
            { spellId: 12878, description: 'Increases the melee attack power reduction of your Demoralizing Shout by 32%.' },
            { spellId: 12879, description: 'Increases the melee attack power reduction of your Demoralizing Shout by 40%.' }
          ],
        },
        {
          id: 'warrior-fury-unbridled-wrath',
          name: 'Unbridled Wrath',
          icon: 'spell_nature_stoneclawtotem',
          row: 1,
          column: 2,
          requiredPoints: 5,
          maxRank: 5,
          ranks: [
            { spellId: 12322, description: 'Gives you a 8% chance to generate an additional Rage point when you deal melee damage with a weapon.' },
            { spellId: 12999, description: 'Gives you a 16% chance to generate an additional Rage point when you deal melee damage with a weapon.' },
            { spellId: 13000, description: 'Gives you a 24% chance to generate an additional Rage point when you deal melee damage with a weapon.' },
            { spellId: 13001, description: 'Gives you a 32% chance to generate an additional Rage point when you deal melee damage with a weapon.' },
            { spellId: 13002, description: 'Gives you a 40% chance to generate an additional Rage point when you deal melee damage with a weapon.' }
          ],
        },
        {
          id: 'warrior-fury-improved-cleave',
          name: 'Improved Cleave',
          icon: 'ability_warrior_cleave',
          row: 2,
          column: 0,
          requiredPoints: 10,
          maxRank: 3,
          ranks: [
            { spellId: 12329, description: 'Increases the bonus damage done by your Cleave ability by 40%.' },
            { spellId: 12950, description: 'Increases the bonus damage done by your Cleave ability by 80%.' },
            { spellId: 20496, description: 'Increases the bonus damage done by your Cleave ability by 120%.' }
          ],
        },
        {
          id: 'warrior-fury-piercing-howl',
          name: 'Piercing Howl',
          icon: 'spell_shadow_deathscream',
          row: 2,
          column: 1,
          requiredPoints: 10,
          maxRank: 1,
          ranks: [
            { spellId: 12323, description: 'Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 seconds.' }
          ],
        },
        {
          id: 'warrior-fury-blood-craze',
          name: 'Blood Craze',
          icon: 'spell_shadow_summonimp',
          row: 2,
          column: 2,
          requiredPoints: 10,
          maxRank: 3,
          ranks: [
            { spellId: 16487, description: 'Regenerates 1% of your total Health over 6 seconds after being the victim of a critical strike.' },
            { spellId: 16489, description: 'Regenerates 2% of your total Health over 6 seconds after being the victim of a critical strike.' },
            { spellId: 16492, description: 'Regenerates 3% of your total Health over 6 seconds after being the victim of a critical strike.' }
          ],
        },
        {
          id: 'warrior-fury-improved-battle-shout',
          name: 'Improved Battle Shout',
          icon: 'ability_warrior_battleshout',
          row: 2,
          column: 3,
          requiredPoints: 10,
          maxRank: 5,
          ranks: [
            { spellId: 12318, description: 'Increases the melee attack power bonus of your Battle Shout by 5%.' },
            { spellId: 12857, description: 'Increases the melee attack power bonus of your Battle Shout by 10%.' },
            { spellId: 12858, description: 'Increases the melee attack power bonus of your Battle Shout by 15%.' },
            { spellId: 12860, description: 'Increases the melee attack power bonus of your Battle Shout by 20%.' },
            { spellId: 12861, description: 'Increases the melee attack power bonus of your Battle Shout by 25%.' }
          ],
        },
        {
          id: 'warrior-fury-dual-wield-specialization',
          name: 'Dual Wield Specialization',
          icon: 'ability_dualwield',
          row: 3,
          column: 0,
          requiredPoints: 15,
          maxRank: 5,
          ranks: [
            { spellId: 23584, description: 'Increases the damage done by your offhand weapon by 5%.' },
            { spellId: 23585, description: 'Increases the damage done by your offhand weapon by 10%.' },
            { spellId: 23586, description: 'Increases the damage done by your offhand weapon by 15%.' },
            { spellId: 23587, description: 'Increases the damage done by your offhand weapon by 20%.' },
            { spellId: 23588, description: 'Increases the damage done by your offhand weapon by 25%.' }
          ],
        },
        {
          id: 'warrior-fury-improved-execute',
          name: 'Improved Execute',
          icon: 'inv_sword_48',
          row: 3,
          column: 1,
          requiredPoints: 15,
          maxRank: 2,
          ranks: [
            { spellId: 20502, description: 'Reduces the Rage cost of your Execute ability by 2.' },
            { spellId: 20503, description: 'Reduces the Rage cost of your Execute ability by 5.' }
          ],
        },
        {
          id: 'warrior-fury-enrage',
          name: 'Enrage',
          icon: 'spell_shadow_unholyfrenzy',
          row: 3,
          column: 2,
          requiredPoints: 15,
          maxRank: 5,
          ranks: [
            { spellId: 12317, description: 'Gives you a 5% melee damage bonus for 12 seconds up to a maximum of 12 swings after being the victim of a critical strike.' },
            { spellId: 13045, description: 'Gives you a 10% melee damage bonus for 12 seconds up to a maximum of 12 swings after being the victim of a critical strike.' },
            { spellId: 13046, description: 'Gives you a 15% melee damage bonus for 12 seconds up to a maximum of 12 swings after being the victim of a critical strike.' },
            { spellId: 13047, description: 'Gives you a 20% melee damage bonus for 12 seconds up to a maximum of 12 swings after being the victim of a critical strike.' },
            { spellId: 13048, description: 'Gives you a 25% melee damage bonus for 12 seconds up to a maximum of 12 swings after being the victim of a critical strike.' }
          ],
        },
        {
          id: 'warrior-fury-improved-slam',
          name: 'Improved Slam',
          icon: 'ability_warrior_decisivestrike',
          row: 4,
          column: 0,
          requiredPoints: 20,
          maxRank: 5,
          ranks: [
            { spellId: 12862, description: 'Decreases the casting time of your Slam ability by 0.1 second.' },
            { spellId: 12330, description: 'Decreases the casting time of your Slam ability by 0.2 second.' },
            { spellId: 20497, description: 'Decreases the casting time of your Slam ability by 0.3 second.' },
            { spellId: 20498, description: 'Decreases the casting time of your Slam ability by 0.4 second.' },
            { spellId: 20499, description: 'Decreases the casting time of your Slam ability by 0.5 second.' }
          ],
        },
        {
          id: 'warrior-fury-death-wish',
          name: 'Death Wish',
          icon: 'spell_shadow_deathpact',
          row: 4,
          column: 1,
          requiredPoints: 20,
          maxRank: 1,
          ranks: [
            { spellId: 12328, description: 'When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%.  Lasts 30 seconds.' }
          ],
        },
        {
          id: 'warrior-fury-improved-intercept',
          name: 'Improved Intercept',
          icon: 'ability_rogue_sprint',
          row: 4,
          column: 3,
          requiredPoints: 20,
          maxRank: 2,
          ranks: [
            { spellId: 20504, description: 'Reduces the cooldown of your Intercept ability by 5 seconds.' },
            { spellId: 20505, description: 'Reduces the cooldown of your Intercept ability by 10 seconds.' }
          ],
        },
        {
          id: 'warrior-fury-improved-berserker-rage',
          name: 'Improved Berserker Rage',
          icon: 'spell_nature_ancestralguardian',
          row: 5,
          column: 0,
          requiredPoints: 25,
          maxRank: 2,
          ranks: [
            { spellId: 20500, description: 'The Berserker Rage ability will generate 5 rage when used.' },
            { spellId: 20501, description: 'The Berserker Rage ability will generate 10 rage when used.' }
          ],
        },
        {
          id: 'warrior-fury-flurry',
          name: 'Flurry',
          icon: 'ability_ghoulfrenzy',
          row: 5,
          column: 2,
          requiredPoints: 25,
          maxRank: 5,
          ranks: [
            { spellId: 12319, description: 'Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.' },
            { spellId: 12971, description: 'Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike.' },
            { spellId: 12972, description: 'Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike.' },
            { spellId: 12973, description: 'Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike.' },
            { spellId: 12974, description: 'Increases your attack speed by 30% for your next 3 swings after dealing a melee critical strike.' }
          ],
          prerequisite: { talentId: 'warrior-fury-enrage', requiredRank: 5 },
        },
        {
          id: 'warrior-fury-bloodthirst',
          name: 'Bloodthirst',
          icon: 'spell_nature_bloodlust',
          row: 6,
          column: 1,
          requiredPoints: 30,
          maxRank: 1,
          ranks: [
            { spellId: 23881, description: 'Instantly attack the target causing damage equal to 45% of your attack power.  In addition, the next 5 successful melee attacks will restore 10 health.  This effect lasts 8 seconds.' }
          ],
          prerequisite: { talentId: 'warrior-fury-death-wish', requiredRank: 1 },
        }
      ],
    },
    {
      id: 'warrior-protection',
      name: 'Protection',
      order: 2,
      talents: [
        {
          id: 'warrior-protection-shield-specialization',
          name: 'Shield Specialization',
          icon: 'inv_shield_06',
          row: 0,
          column: 1,
          requiredPoints: 0,
          maxRank: 5,
          ranks: [
            { spellId: 12298, description: 'Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.' },
            { spellId: 12724, description: 'Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 1 rage when a block occurs.' },
            { spellId: 12725, description: 'Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 1 rage when a block occurs.' },
            { spellId: 12726, description: 'Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 1 rage when a block occurs.' },
            { spellId: 12727, description: 'Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 1 rage when a block occurs.' }
          ],
        },
        {
          id: 'warrior-protection-anticipation',
          name: 'Anticipation',
          icon: 'spell_nature_mirrorimage',
          row: 0,
          column: 2,
          requiredPoints: 0,
          maxRank: 5,
          ranks: [
            { spellId: 12297, description: 'Increases your Defense skill by 2.' },
            { spellId: 12750, description: 'Increases your Defense skill by 4.' },
            { spellId: 12751, description: 'Increases your Defense skill by 6.' },
            { spellId: 12752, description: 'Increases your Defense skill by 8.' },
            { spellId: 12753, description: 'Increases your Defense skill by 10.' }
          ],
        },
        {
          id: 'warrior-protection-improved-bloodrage',
          name: 'Improved Bloodrage',
          icon: 'ability_racial_bloodrage',
          row: 1,
          column: 0,
          requiredPoints: 5,
          maxRank: 2,
          ranks: [
            { spellId: 12301, description: 'Increases the instant Rage generated by your Bloodrage ability by 2.' },
            { spellId: 12818, description: 'Increases the instant Rage generated by your Bloodrage ability by 5.' }
          ],
        },
        {
          id: 'warrior-protection-toughness',
          name: 'Toughness',
          icon: 'spell_holy_devotion',
          row: 1,
          column: 2,
          requiredPoints: 5,
          maxRank: 5,
          ranks: [
            { spellId: 12299, description: 'Increases your armor value from items by 2%.' },
            { spellId: 12761, description: 'Increases your armor value from items by 4%.' },
            { spellId: 12762, description: 'Increases your armor value from items by 6%.' },
            { spellId: 12763, description: 'Increases your armor value from items by 8%.' },
            { spellId: 12764, description: 'Increases your armor value from items by 10%.' }
          ],
        },
        {
          id: 'warrior-protection-iron-will',
          name: 'Iron Will',
          icon: 'spell_magic_magearmor',
          row: 1,
          column: 3,
          requiredPoints: 5,
          maxRank: 5,
          ranks: [
            { spellId: 12300, description: 'Increases your chance to resist Stun and Charm effects by an additional 3%.' },
            { spellId: 12959, description: 'Increases your chance to resist Stun and Charm effects by an additional 6%.' },
            { spellId: 12960, description: 'Increases your chance to resist Stun and Charm effects by an additional 9%.' },
            { spellId: 12961, description: 'Increases your chance to resist Stun and Charm effects by an additional 12%.' },
            { spellId: 12962, description: 'Increases your chance to resist Stun and Charm effects by an additional 15%.' }
          ],
        },
        {
          id: 'warrior-protection-last-stand',
          name: 'Last Stand',
          icon: 'spell_holy_ashestoashes',
          row: 2,
          column: 0,
          requiredPoints: 10,
          maxRank: 1,
          ranks: [
            { spellId: 12975, description: 'When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds.  After the effect expires, the hit points are lost.' }
          ],
          prerequisite: { talentId: 'warrior-protection-improved-bloodrage', requiredRank: 2 },
        },
        {
          id: 'warrior-protection-improved-shield-block',
          name: 'Improved Shield Block',
          icon: 'ability_defend',
          row: 2,
          column: 1,
          requiredPoints: 10,
          maxRank: 3,
          ranks: [
            { spellId: 12945, description: 'Allows your Shield Block ability to block an additional attack and increases the duration by 0.5 second.' },
            { spellId: 12307, description: 'Allows your Shield Block ability to block an additional attack and increases the duration by 1 second.' },
            { spellId: 12944, description: 'Allows your Shield Block ability to block an additional attack and increases the duration by 2 seconds.' }
          ],
          prerequisite: { talentId: 'warrior-protection-shield-specialization', requiredRank: 5 },
        },
        {
          id: 'warrior-protection-improved-revenge',
          name: 'Improved Revenge',
          icon: 'ability_warrior_revenge',
          row: 2,
          column: 2,
          requiredPoints: 10,
          maxRank: 3,
          ranks: [
            { spellId: 12797, description: 'Gives your Revenge ability a 15% chance to stun the target for 3 seconds.' },
            { spellId: 12799, description: 'Gives your Revenge ability a 30% chance to stun the target for 3 seconds.' },
            { spellId: 12800, description: 'Gives your Revenge ability a 45% chance to stun the target for 3 seconds.' }
          ],
        },
        {
          id: 'warrior-protection-defiance',
          name: 'Defiance',
          icon: 'ability_warrior_innerrage',
          row: 2,
          column: 3,
          requiredPoints: 10,
          maxRank: 5,
          ranks: [
            { spellId: 12303, description: 'Increases the threat generated by your attacks by 3% while in Defensive Stance.' },
            { spellId: 12788, description: 'Increases the threat generated by your attacks by 6% while in Defensive Stance.' },
            { spellId: 12789, description: 'Increases the threat generated by your attacks by 9% while in Defensive Stance.' },
            { spellId: 12791, description: 'Increases the threat generated by your attacks by 12% while in Defensive Stance.' },
            { spellId: 12792, description: 'Increases the threat generated by your attacks by 15% while in Defensive Stance.' }
          ],
        },
        {
          id: 'warrior-protection-improved-sunder-armor',
          name: 'Improved Sunder Armor',
          icon: 'ability_warrior_sunder',
          row: 3,
          column: 0,
          requiredPoints: 15,
          maxRank: 3,
          ranks: [
            { spellId: 12308, description: 'Reduces the cost of your Sunder Armor ability by 1 rage point.' },
            { spellId: 12810, description: 'Reduces the cost of your Sunder Armor ability by 2 rage points.' },
            { spellId: 12811, description: 'Reduces the cost of your Sunder Armor ability by 3 rage points.' }
          ],
        },
        {
          id: 'warrior-protection-improved-disarm',
          name: 'Improved Disarm',
          icon: 'ability_warrior_disarm',
          row: 3,
          column: 1,
          requiredPoints: 15,
          maxRank: 3,
          ranks: [
            { spellId: 12313, description: 'Increases the duration of your Disarm ability by 1 seconds.' },
            { spellId: 12804, description: 'Increases the duration of your Disarm ability by 2 seconds.' },
            { spellId: 12807, description: 'Increases the duration of your Disarm ability by 3 seconds.' }
          ],
        },
        {
          id: 'warrior-protection-improved-taunt',
          name: 'Improved Taunt',
          icon: 'spell_nature_reincarnation',
          row: 3,
          column: 2,
          requiredPoints: 15,
          maxRank: 2,
          ranks: [
            { spellId: 12302, description: 'Reduces the cooldown of your Taunt ability by 1 second.' },
            { spellId: 12765, description: 'Reduces the cooldown of your Taunt ability by 2 seconds.' }
          ],
        },
        {
          id: 'warrior-protection-improved-shield-wall',
          name: 'Improved Shield Wall',
          icon: 'ability_warrior_shieldwall',
          row: 4,
          column: 0,
          requiredPoints: 20,
          maxRank: 2,
          ranks: [
            { spellId: 12312, description: 'Increases the effect duration of your Shield Wall ability by 3 seconds.' },
            { spellId: 12803, description: 'Increases the effect duration of your Shield Wall ability by 5 seconds.' }
          ],
        },
        {
          id: 'warrior-protection-concussion-blow',
          name: 'Concussion Blow',
          icon: 'ability_thunderbolt',
          row: 4,
          column: 1,
          requiredPoints: 20,
          maxRank: 1,
          ranks: [
            { spellId: 12809, description: 'Stuns the opponent for 5 seconds.' }
          ],
        },
        {
          id: 'warrior-protection-improved-shield-bash',
          name: 'Improved Shield Bash',
          icon: 'ability_warrior_shieldbash',
          row: 4,
          column: 2,
          requiredPoints: 20,
          maxRank: 2,
          ranks: [
            { spellId: 12311, description: 'Gives your Shield Bash ability a 50% chance to silence the target for 3 seconds.' },
            { spellId: 12958, description: 'Gives your Shield Bash ability a 100% chance to silence the target for 3 seconds.' }
          ],
        },
        {
          id: 'warrior-protection-one-handed-weapon-specialization',
          name: 'One-Handed Weapon Specialization',
          icon: 'inv_sword_20',
          row: 5,
          column: 2,
          requiredPoints: 25,
          maxRank: 5,
          ranks: [
            { spellId: 16538, description: 'Increases the damage you deal with One-Handed Melee weapons by 2%.' },
            { spellId: 16539, description: 'Increases the damage you deal with One-Handed Melee weapons by 4%.' },
            { spellId: 16540, description: 'Increases the damage you deal with One-Handed Melee weapons by 6%.' },
            { spellId: 16541, description: 'Increases the damage you deal with One-Handed Melee weapons by 8%.' },
            { spellId: 16542, description: 'Increases the damage you deal with One-Handed Melee weapons by 10%.' }
          ],
        },
        {
          id: 'warrior-protection-shield-slam',
          name: 'Shield Slam',
          icon: 'inv_shield_05',
          row: 6,
          column: 1,
          requiredPoints: 30,
          maxRank: 1,
          ranks: [
            { spellId: 23922, description: 'Slam the target with your shield, causing 225 to 235 damage, modified by your shield block value, and has a 50% chance of dispelling 1 magic effect on the target.  Also causes a high amount of threat.' }
          ],
          prerequisite: { talentId: 'warrior-protection-concussion-blow', requiredRank: 1 },
        }
      ],
    }
  ],
}
