import InfoPageLayout, { type InfoSection } from '../components/layout/InfoPageLayout'

const sections: InfoSection[] = [
  { id: 'information', title: 'Information we collect', content: <><p>WoWiki collects information you choose to provide when you create an account, publish an entry, comment, contact support, or subscribe to updates. This may include a display name, email address, profile preferences, and the content you submit.</p><p>We also receive limited technical data such as browser type, approximate region, referring pages, device information, and interaction events. We use this operational data to keep the service reliable, understand feature usage, and prevent abuse.</p></> },
  { id: 'use', title: 'How information is used', content: <><p>We use account and activity data to operate WoWiki, display community contributions, personalize saved content, answer support requests, enforce community standards, and improve guides and discovery tools.</p><ul className="list-disc space-y-2 pl-5"><li>Deliver requested pages and account features.</li><li>Protect accounts and investigate spam, fraud, or harmful behavior.</li><li>Measure performance and diagnose technical problems.</li><li>Send service notices and optional communications you request.</li></ul><p>WoWiki does not sell personal information or use private account data to build third-party advertising profiles.</p></> },
  { id: 'public-content', title: 'Public community content', content: <><p>Entries, comments, replies, reactions, and public profile details are visible to other visitors. Search engines may index public pages. Do not include private information in content intended for the community.</p><p>Removing an account may detach or anonymize contributions when retaining them is necessary to preserve discussion context. Content removed for safety or legal reasons may remain in restricted backups for a limited period.</p></> },
  { id: 'cookies', title: 'Cookies and local storage', content: <><p>WoWiki uses essential browser storage to maintain sessions, remember preferences, and support features such as saved articles and reactions. We may use privacy-conscious analytics to understand aggregate traffic and page performance.</p><p>You can clear stored preferences through your browser. Blocking essential storage may prevent sign-in and personalized features from working correctly.</p></> },
  { id: 'sharing', title: 'When information is shared', content: <><p>Information may be processed by carefully selected infrastructure, security, email, and analytics providers working on our behalf. They may only use it to deliver contracted services and must protect it appropriately.</p><p>We may disclose information when required by law, to address an immediate safety risk, to defend legal rights, or as part of a merger or transfer of the service. We will provide notice when legally permitted and reasonably possible.</p></> },
  { id: 'retention', title: 'Retention and security', content: <><p>We retain personal information only while it serves the purposes described here, meets legal obligations, resolves disputes, or protects the community. Retention periods vary by data type and account status.</p><p>We use access controls, encrypted transport, backups, monitoring, and least-privilege practices. No online service can guarantee absolute security, so report suspected account or data issues promptly.</p></> },
  { id: 'rights', title: 'Your choices and rights', content: <><p>You may request access, correction, export, restriction, objection, or deletion where applicable. You can also withdraw optional consent and unsubscribe from non-essential email.</p><p>Requests can be sent through the Contact page. We may verify identity before completing a request and will explain when a legal exception applies.</p></> },
  { id: 'children', title: 'Children and international use', content: <><p>WoWiki is not directed to children under 13, or the minimum digital-consent age required in their country. We do not knowingly collect personal information from children who cannot legally provide consent.</p><p>Information may be processed in countries other than your own. Where required, we use recognized safeguards for international transfers.</p></> },
  { id: 'changes', title: 'Policy changes', content: <p>We may update this policy as WoWiki grows or legal requirements change. Material changes will be announced through the service or by email when appropriate. Continued use after an effective date means the revised policy applies.</p> },
]

export default function PrivacyPage(): JSX.Element {
  return <InfoPageLayout eyebrow="Your data" title="Privacy Policy" summary="How WoWiki collects, uses, protects, and gives you control over information connected to the encyclopedia and its community features." updated="July 12, 2026" sections={sections} />
}
