import InfoPageLayout, { type InfoSection } from '../components/layout/InfoPageLayout'

const sections: InfoSection[] = [
  { id: 'agreement', title: 'Agreement and eligibility', content: <><p>These terms govern access to WoWiki, including its articles, tools, community entries, comments, and account features. By using the service, you agree to these terms and the Privacy Policy.</p><p>You must be legally able to enter this agreement. If you use WoWiki for an organization, you confirm that you can bind that organization to these terms.</p></> },
  { id: 'accounts', title: 'Accounts and security', content: <><p>Provide accurate registration information and keep credentials secure. You are responsible for activity performed through your account unless you promptly report unauthorized access.</p><p>Display names must not impersonate others, misrepresent affiliation, or violate community standards. We may reclaim names needed to address trademark, impersonation, or safety concerns.</p></> },
  { id: 'conduct', title: 'Community conduct', content: <><p>Contribute constructively and treat other members with respect. Do not post harassment, threats, hate, sexual exploitation, private information, malware, spam, deceptive promotions, or content that facilitates unlawful activity.</p><p>Do not manipulate reactions, evade moderation, scrape the service disruptively, probe security without permission, or automate account activity in ways that degrade WoWiki.</p></> },
  { id: 'contributions', title: 'Your contributions', content: <><p>You retain ownership of original content you submit. You grant WoWiki a worldwide, non-exclusive, royalty-free license to host, reproduce, format, distribute, display, and adapt that content for operating, promoting, and improving the service.</p><p>You confirm that you have the rights needed to submit content. Community edits may be revised, summarized, linked, moderated, or removed to maintain accuracy, safety, and readability.</p></> },
  { id: 'accuracy', title: 'Editorial accuracy and game information', content: <><p>WoWiki is community-driven. Guides, lore analysis, statistics, and recommendations may become incomplete or outdated as the game changes. Verify critical game decisions against current official sources and patch notes.</p><p>Opinions expressed by contributors belong to those contributors and do not necessarily represent WoWiki.</p></> },
  { id: 'intellectual-property', title: 'Intellectual property', content: <><p>WoWiki software, layout, and original editorial materials are protected by applicable intellectual-property laws. Limited personal, non-commercial use is permitted unless a page states another license.</p><p>World of Warcraft, Warcraft, Blizzard Entertainment, and related names and assets belong to their respective owners. WoWiki is an independent community project and is not endorsed by or affiliated with Blizzard Entertainment.</p></> },
  { id: 'moderation', title: 'Moderation and enforcement', content: <><p>We may investigate reports and remove content, restrict features, suspend accounts, or terminate access when reasonably necessary to enforce these terms, protect users, or comply with law.</p><p>Moderation decisions consider context, severity, history, and risk. You may contact us to request review, but we cannot guarantee restoration of content or access.</p></> },
  { id: 'disclaimers', title: 'Disclaimers and liability', content: <><p>WoWiki is provided “as is” and “as available” without warranties of uninterrupted operation, accuracy, fitness for a particular purpose, or non-infringement to the extent permitted by law.</p><p>To the maximum extent permitted by law, WoWiki and its operators are not liable for indirect, incidental, special, consequential, or punitive damages arising from use of the service. Mandatory consumer rights remain unaffected.</p></> },
  { id: 'changes', title: 'Changes and contact', content: <><p>We may change features or these terms as the project evolves. Material revisions will be announced reasonably in advance when possible. If you disagree with revised terms, stop using the service before they take effect.</p><p>Questions about these terms can be sent through the Contact page.</p></> },
]

export default function TermsPage(): JSX.Element {
  return <InfoPageLayout eyebrow="Community agreement" title="Terms of Use" summary="The rules that keep WoWiki useful, trustworthy, and welcoming for readers, editors, guide writers, and community contributors." updated="July 12, 2026" sections={sections} />
}
